/**
 * Test image fixtures - loads pre-generated PNG images for E2E tests
 *
 * These images are 400x400 pixels and are large enough to require scrolling.
 * They are generated by generate-test-images.cjs and stored as PNG files.
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const fixturesDir = dirname(__filename);

/**
 * Load a test image buffer by name
 */
function loadTestImage(filename: string): Buffer {
  return readFileSync(join(fixturesDir, filename));
}

/**
 * Pre-generated test images
 */
export const TEST_IMAGES = {
  red400x400: loadTestImage('red-400x400.png'),
  blue400x400: loadTestImage('blue-400x400.png'),
  green400x400: loadTestImage('green-400x400.png'),
};
